# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02cfd13a9578cd027b751390aa4ffbd302ade8b068cba7b71fb8e3cf0828914106f1eb964dc636b39d52937fe41dff00987a0a8819fd14ce1362d67f7fee3dbe

test:
  secret_key_base: 060b1391398edacc2a2a63c2906656e16fbabd479ff2620a916b9179d26ed0be2702d5b5eac956b88855ba9284b0e9e0115a84e51ae7903bf211fe8c3a5d1f82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
